import { NextPage } from 'next';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@primer-io/goat';

const Success: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Success</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href={'/'} passHref><Button as={'a'}>Go Back</Button></Link>
                <h1 className={styles.title}>Success</h1>
                <p className={styles.description}>You bought the spaceship!</p>
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Success;
