import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Nauvoo from '../public/images/S02e04nauvoo16m00s.webp';
import Rocinante from '../public/images/RociArtS4.webp';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>{' '}
                    <svg width="27" height="47" viewBox="0 0 27 47" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M24.7543 13.513H17.3264C15.2144 13.513 13.5 11.8006 13.5 9.68381V6.75486C13.5 3.02354 10.4786 0 6.75 0C3.02137 0 0 3.02354 0 6.75486C0 10.4862 3.02137 13.5097 6.75 13.5097H9.67684C11.7889 13.5097 13.5033 15.2253 13.5033 17.3389V24.3188C13.5033 26.4323 11.7889 28.148 9.67684 28.148H6.75C3.02137 28.148 0 31.1715 0 34.9028V39.7887C0 43.5201 3.02137 46.5436 6.75 46.5436C10.4786 46.5436 13.5 43.5201 13.5 39.7887V34.9028V31.9739C13.5 29.8603 15.2111 28.1447 17.3264 28.1447H24.7511C25.9929 28.1447 27 27.1368 27 25.8942V15.7635C27.0033 14.5208 25.9961 13.513 24.7543 13.513Z"
                            fill="#000"
                        ></path>
                    </svg>
                    Primer Example
                </h1>

                <p className={styles.description}>
                    Little test to see how primer checkout works with modern frameworks.
                </p>

                <div className={styles.grid}>
                    <Link href="buy/nauvoo" passHref>
                        <a className={styles.card}>
                            <h2>Nauvoo / Behemoth &rarr;</h2>
                            <Image src={Nauvoo} alt="Picture of Nauvoo" />
                        </a>
                    </Link>
                    <Link href="buy/rocinante" passHref>
                        <a className={styles.card}>
                            <h2>Rocinante &rarr;</h2>
                            <Image src={Rocinante} alt="Picture of Rocinante" />
                        </a>
                    </Link>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
